---
- hosts: all
  connection: local

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: ansible-role-homebrew
      tags: ['homebrew']
    - role: ansible-role-mas
      when: mas_installed_apps
      tags: ['mas']
    - role: ansible-role-dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
